In [10]:
import numpy as np
from scipy import constants
import tabulate
import pandas as pd
import matplotlib.pyplot as plt
from IonChainTools import calcPositions,lengthScale
from tweezer_functions import *

In [11]:
#Constants in SI units
eps0 = constants.epsilon_0 
m = 39.9626*constants.atomic_mass
c = constants.c
e = constants.e
hbar = constants.hbar
pi = np.pi

In [12]:
#number of ions
N = 12
#tweezed ions is an adjustable parameter
tweezed_ions = [0,1,5,6,10,11]


#radial and axial frequencies of the blade trap
w_rf_r = 2*pi*3e6
w_rf_a = 2*pi*0.5e6

#radial and axial frequencies of tweezer trap
w_tweezer_r = 2*pi*1e6
w_tweezer_a = 2*pi*0.2*1e6

In [13]:
individual_freqs_to_mode_vectors(N,tweezed_ions,w_tweezer_r,w_tweezer_a,w_rf_r,w_rf_a)

[(3111393.1886459077,
  array([0.51674769, 0.34846645, 0.19187087, 0.1506038 , 0.14560782,
         0.17562854, 0.17562854, 0.14560782, 0.1506038 , 0.19187087,
         0.34846645, 0.51674769])),
 (3099732.2825345164,
  array([-0.58197798, -0.35297391, -0.16178755, -0.08950027, -0.04723449,
         -0.01715923,  0.01715923,  0.04723449,  0.08950027,  0.16178755,
          0.35297391,  0.58197798])),
 (3020435.3909353125,
  array([ 0.34911383,  0.01288126, -0.12523291, -0.22516568, -0.32155098,
         -0.45626276, -0.45626276, -0.32155098, -0.22516568, -0.12523291,
          0.01288126,  0.34911383])),
 (2907523.719878225,
  array([ 0.38169025, -0.39043306, -0.32594507, -0.2538538 , -0.16349275,
         -0.06680389,  0.06680389,  0.16349275,  0.2538538 ,  0.32594507,
          0.39043306, -0.38169025])),
 (2862557.3653213293,
  array([ 0.32699572, -0.49352755, -0.2574064 , -0.06119964,  0.10994679,
          0.25963938,  0.25963938,  0.10994679, -0.06119964, -0.2574064 ,
         -0