In [1]:
import numpy as np
from scipy import constants
import tabulate
import pandas as pd
import matplotlib.pyplot as plt
from IonChainTools import calcPositions,lengthScale
from tweezer_functions import *

In [2]:
#Constants in SI units
eps0 = constants.epsilon_0 
m = 39.9626*constants.atomic_mass
c = constants.c
e = constants.e
hbar = constants.hbar
pi = np.pi

In [3]:
N = 12
#tweezed ions is an adjustable parameter
tweezed_ions = [0,1,5,6,10,11]
#radial and axial frequencies of the blade trap

w_rf_r = 1.0 * pi * 1e6 *2
w_rf_a = w_rf_r /8

NA = 0.6
wx = 2*pi*1e6
d = 5e-6
tweezer_wavelength = 532*1e9
P_opt = 15e-3
omega_tweezer = 2*pi*c/tweezer_wavelength
df = pd.read_csv('S_P_only.csv',sep = ",",encoding='UTF-8')

lambdares = df["wavelength (nm)"]
lambdares = [i*1e-9 for i in lambdares]
omegares = [2*pi*c/i for i in lambdares]
print(omegares)
lifetimes = df["A_ki (s^-1)"]
lifetimes = [i for i in lifetimes]
omega_res = np.array(omegares)
linewidths = np.array(lifetimes)


beam_waist = 0.41*tweezer_wavelength / NA

[4788543317790194.0, 4746544743851730.0]


In [4]:
physical_params_to_radial_mode_vectors(N,tweezed_ions,omega_tweezer,tweezer_wavelength,linewidths,omega_res,w_rf_a,w_rf_r,P_opt,beam_waist,m)

[(1000000.0000000001,
  array([0.28867513, 0.28867513, 0.28867513, 0.28867513, 0.28867513,
         0.28867513, 0.28867513, 0.28867513, 0.28867513, 0.28867513,
         0.28867513, 0.28867513])),
 (992156.7416596987,
  array([-0.4815668 , -0.37106508, -0.27873523, -0.19479282, -0.11535286,
         -0.03821345,  0.03821345,  0.11535286,  0.19479282,  0.27873523,
          0.37106508,  0.4815668 ])),
 (980883.8816819862,
  array([ 0.53408894,  0.19502832, -0.02049328, -0.16314016, -0.25150555,
         -0.29397828, -0.29397828, -0.25150555, -0.16314016, -0.02049328,
          0.19502832,  0.53408894])),
 (966520.8689891044,
  array([-0.46802846,  0.11797224,  0.316344  ,  0.32620253,  0.23169103,
          0.0828828 , -0.0828828 , -0.23169103, -0.32620253, -0.316344  ,
         -0.11797224,  0.46802846])),
 (949228.9068865108,
  array([ 0.34283993, -0.38533365, -0.33429551, -0.0827221 ,  0.15973065,
          0.29978067,  0.29978067,  0.15973065, -0.0827221 , -0.33429551,
         -0.38