In [5]:
import numpy as np
from scipy import constants
import tabulate
import pandas as pd
import matplotlib.pyplot as plt
from IonChainTools import calcPositions,lengthScale
from tweezer_functions import *

In [6]:
#Constants in SI units
eps0 = constants.epsilon_0 
m = 39.9626*constants.atomic_mass
c = constants.c
e = constants.e
hbar = constants.hbar
pi = np.pi

In [8]:
N = 12
#tweezed ions is an adjustable parameter
tweezed_ions = [0,1,5,6,10,11]
#radial and axial frequencies of the blade trap

w_rf_r = 1.0 * pi * 1e6 *2
w_rf_a = w_rf_r /8

NA = 0.6
d = 5e-6
tweezer_wavelength = 532*1e-9
P_opt = 15e-3
omega_tweezer = 2*pi*c/tweezer_wavelength
df = pd.read_csv('S_P_only.csv',sep = ",",encoding='UTF-8')

lambdares = df["wavelength (nm)"]
lambdares = [i*1e-9 for i in lambdares]
omegares = [2*pi*c/i for i in lambdares]
print(omegares)
lifetimes = df["A_ki (s^-1)"]
lifetimes = [i for i in lifetimes]
omega_res = np.array(omegares)
linewidths = np.array(lifetimes)


beam_waist = 0.41*tweezer_wavelength / NA

[4788543317790194.0, 4746544743851730.0]


In [9]:

physical_params_to_radial_mode_vectors(N,tweezed_ions,tweezer_wavelength,linewidths,omega_res,w_rf_a,w_rf_r,P_opt,beam_waist,m)


[(1167253.4786396543,
  array([0.63264429, 0.30980772, 0.04914822, 0.01850789, 0.01343989,
         0.02901144, 0.02901144, 0.01343989, 0.01850789, 0.04914822,
         0.30980772, 0.63264429])),
 (1167027.281368155,
  array([-0.63477792, -0.30746618, -0.04734946, -0.01523016, -0.00604469,
         -0.00332799,  0.00332799,  0.00604469,  0.01523016,  0.04734946,
          0.30746618,  0.63477792])),
 (1129438.6441048547,
  array([ 0.14185092, -0.21014246, -0.05503547, -0.07175871, -0.17042774,
         -0.63126432, -0.63126432, -0.17042774, -0.07175871, -0.05503547,
         -0.21014246,  0.14185092])),
 (1123709.2215577776,
  array([-0.31153903,  0.62661184,  0.0957111 ,  0.03047021,  0.01222662,
          0.00790502, -0.00790502, -0.01222662, -0.03047021, -0.0957111 ,
         -0.62661184,  0.31153903])),
 (1122904.9378661185,
  array([ 0.28220275, -0.5892373 , -0.08098234, -0.00376426,  0.0567992 ,
          0.25171921,  0.25171921,  0.0567992 , -0.00376426, -0.08098234,
         -0