In [29]:
import numpy as np
from scipy import constants
import tabulate
import pandas as pd
import matplotlib.pyplot as plt
from IonChainTools import calcPositions,lengthScale
from tweezer_functions import *

In [30]:
#Constants in SI units
eps0 = constants.epsilon_0 
m = 39.9626*constants.atomic_mass
c = constants.c
e = constants.e
hbar = constants.hbar
pi = np.pi

In [31]:
N = 12
#tweezed ions is an adjustable parameter
tweezed_ions = [0,1,5,6,10,11]
#radial and axial frequencies of the blade trap

w_rf_r = 1.0 * pi * 1e6 *2
w_rf_a = w_rf_r /8

NA = 0.6
d = 5e-6
tweezer_wavelength = 532*1e-9
P_opt = 15e-3
omega_tweezer = 2*pi*c/tweezer_wavelength
df = pd.read_csv('S_P_only.csv',sep = ",",encoding='UTF-8')

lambdares = df["wavelength (nm)"]
lambdares = [i*1e-9 for i in lambdares]
omegares = [2*pi*c/i for i in lambdares]
lifetimes = df["A_ki (s^-1)"]
lifetimes = [i for i in lifetimes]
omega_res = np.array(omegares)
linewidths = np.array(lifetimes)
beam_waist = 0.41*tweezer_wavelength / NA
ueq = ion_spacing(N, w_rf_a)[0]
U = potential(omega_tweezer,linewidths,omega_res,P_opt,beam_waist)

In [28]:
physical_params_to_radial_mode_vectors(N, ueq, tweezed_ions, tweezer_wavelength, linewidths, omega_res, w_rf_a, w_rf_r, P_opt, beam_waist, m, U)

[(1358046.8607450156,
  array([-0.64078533, -0.29739433, -0.02410275, -0.00692953, -0.00471901,
         -0.01730738, -0.01730738, -0.00471901, -0.00692953, -0.02410275,
         -0.29739433, -0.64078533])),
 (1357909.1688956819,
  array([ 0.64179688,  0.29580385,  0.02352632,  0.00594359,  0.00214831,
          0.00184828, -0.00184828, -0.00214831, -0.00594359, -0.02352632,
         -0.29580385, -0.64179688])),
 (1320325.6024901746,
  array([-0.26122815,  0.53643667,  0.04188202,  0.02125336,  0.05250367,
          0.37287143,  0.37287143,  0.05250367,  0.02125336,  0.04188202,
          0.53643668, -0.26122815])),
 (1319602.4230946677,
  array([ 0.29679774, -0.64012536, -0.04503599, -0.00997648, -0.00332905,
         -0.00343008,  0.00343008,  0.00332905,  0.00997648,  0.04503599,
          0.64012536, -0.29679774])),
 (1317974.212791943,
  array([-0.14541157,  0.34789056,  0.01828618, -0.01457501, -0.07721411,
         -0.59272152, -0.59272152, -0.07721411, -0.01457501,  0.01828618,